/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CCDetect.lsp;

import org.eclipse.lsp4j.jsonrpc.Launcher;
import org.eclipse.lsp4j.launch.LSPLauncher;
import org.eclipse.lsp4j.services.LanguageClient;
import org.eclipse.lsp4j.services.LanguageClientAware;
import org.eclipse.lsp4j.services.LanguageServer;

public class App {

    public static Launcher<LanguageClient> createLauncher(LanguageServer server) {
        Launcher<LanguageClient> launcher = LSPLauncher.createServerLauncher(
            server,
            System.in,
            System.out
        );
        LanguageClient client = launcher.getRemoteProxy();
        ((LanguageClientAware)server).connect(client);

        return launcher;
    }

    public static void main(String[] args) {
        LanguageServer server = new CCLanguageServer();
        Launcher<LanguageClient> launcher = createLauncher(server);
        launcher.startListening();
    }
}
